# Chạy trên Hugging Face (Production)
BACKEND_URL = "https://tuandaca-backend-travelai.hf.space"

# Chạy dưới máy cá nhân (Local) - Khi nào cần chạy local thì bỏ dấu # ở dưới và thêm # ở trên
# BACKEND_URL = "http://127.0.0.1:8000"